---
title: "Preference study"
---


Load data: 

```{r}

library('openxlsx')


path <- '../../../log_data/'

data.raw <- read.xlsx(xlsxFile = paste0(path,'Ratings.xlsx'),sheet= 1)


```

Raster plot function


Preferences: 

```{r}
library('ggplot2')
library('dplyr')

overall.pref <- as.data.frame(table(data.raw$Preference) / sum(table(data.raw$Preference
                                                                     
                                                       ))) 

names(overall.pref) <- c('Program','Preference')

overall.pref$Preference <- overall.pref$Preference * 100

levels(overall.pref$Program)[levels(overall.pref$Program) == 1] <-  names.states[1]
levels(overall.pref$Program)[levels(overall.pref$Program) == 2] <-  names.states[2]
levels(overall.pref$Program)[levels(overall.pref$Program) == 3] <-  names.states[3]
levels(overall.pref$Program)[levels(overall.pref$Program) == 4] <-  names.states[4]


overall.pref %>% ggplot(aes(x= Program,y = Preference)) +
  geom_bar(stat="identity",fill = 'steelblue',width = .8) +
  scale_y_continuous(limits = c(0,100)) +
  labs(title = 'Preference across subjects and scenes') + 
  theme(axis.text = element_text(size = 11),
        axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13))



```

Preferences per scene: 

```{r}

data.car <- data.raw[data.raw$Scene == 'car','Preference'] %>% table() %>% as.data.frame() 
data.meeting <- data.raw[data.raw$Scene == 'meeting','Preference'] %>% table() %>% as.data.frame() 
data.traffic <- data.raw[data.raw$Scene == 'traffic','Preference'] %>% table() %>% as.data.frame() 
data.canteenWO <- data.raw[data.raw$Scene == 'canteen-','Preference'] %>% table() %>% as.data.frame() 
data.canteenW <- data.raw[data.raw$Scene == 'canteen+','Preference'] %>% table() %>% as.data.frame() 

names.states <- c('2-mic PR','MiE','Asym','BBF')

names(data.car) <- c('Program','Preference')
levels(data.car$Program)[levels(data.car$Program) == 1] <- names.states[1]
levels(data.car$Program)[levels(data.car$Program) == 2] <- names.states[2]
levels(data.car$Program)[levels(data.car$Program) == 3] <- names.states[3]
levels(data.car$Program)[levels(data.car$Program) == 4] <- names.states[4]
data.car$scene <- 'car'

data.car$Preference <- data.car$Preference / sum(data.car$Preference) * 100

names(data.meeting) <- c('Program','Preference')
levels(data.meeting$Program)[levels(data.meeting$Program) == 1] <- names.states[1]
levels(data.meeting$Program)[levels(data.meeting$Program) == 2] <- names.states[2]
levels(data.meeting$Program)[levels(data.meeting$Program) == 3] <- names.states[3]
levels(data.meeting$Program)[levels(data.meeting$Program) == 4] <- names.states[4] 
data.meeting$scene <- 'meeting'

data.meeting$Preference <- data.meeting$Preference / sum(data.meeting$Preference) * 100

names(data.traffic) <- c('Program','Preference')
levels(data.traffic$Program)[levels(data.traffic$Program) == 1] <- names.states[1]
levels(data.traffic$Program)[levels(data.traffic$Program) == 2] <-  names.states[2]
levels(data.traffic$Program)[levels(data.traffic$Program) == 3] <-  names.states[3]
levels(data.traffic$Program)[levels(data.traffic$Program) == 4] <-  names.states[4]
data.traffic$scene <- 'traffic'

data.traffic$Preference <- data.traffic$Preference / sum(data.traffic$Preference) * 100


names(data.canteenWO) <- c('Program','Preference')
levels(data.canteenWO$Program)[levels(data.canteenWO$Program) == 1] <-  names.states[1]
levels(data.canteenWO$Program)[levels(data.canteenWO$Program) == 2] <-  names.states[2]
levels(data.canteenWO$Program)[levels(data.canteenWO$Program) == 3] <-  names.states[3]
levels(data.canteenWO$Program)[levels(data.canteenWO$Program) == 4] <-  names.states[4]
data.canteenWO$scene <- 'canteen w/o'

data.canteenWO$Preference <- data.canteenWO$Preference / sum(data.canteenWO$Preference) * 100


names(data.canteenW) <- c('Program','Preference')
levels(data.canteenW$Program)[levels(data.canteenW$Program) == 1] <-  names.states[1]
levels(data.canteenW$Program)[levels(data.canteenW$Program) == 2] <-  names.states[2]
levels(data.canteenW$Program)[levels(data.canteenW$Program) == 3] <-  names.states[3]
levels(data.canteenW$Program)[levels(data.canteenW$Program) == 4] <-  names.states[4]
data.canteenW$scene <- 'canteen 0dB SNR'

data.canteenW$Preference <- data.canteenW$Preference / sum(data.canteenW$Preference) * 100


data.scene.preferences <- rbind(data.car,data.meeting,data.traffic,data.canteenWO,data.canteenW)

png('Preference_scenes.png',width = 1200, height = 600)

data.scene.preferences %>% ggplot(aes(x = Program, y = Preference)) +
  geom_bar(stat='identity',position = 'dodge',fill = 'steelblue',width = .8) + facet_wrap(~scene) +
  theme(axis.text=element_text(size=16,color='black'),
        axis.title=element_text(size=16,face="bold"),
        strip.text.x = element_text(size = 17,face='bold'))


  
dev.off()

```

Preferences across all subjects:

```{r}
library('plot.matrix')
library('dplyr')

Individual_preferences <- matrix(ncol = 15,nrow = 5)

scene_name <- c('car','meeting','canteen+','canteen-','traffic')
names <- names.states#c('2-mic PR / 2-mic PR','MiE / MiE','Monitor / Focus','BBF / BBF')

for (iSubject in 1:15){
  for (iScene in 1:5){
    
    tmp <- data.raw %>% filter(Scene == scene_name[iScene] & Subject == iSubject) 
    Individual_preferences[iScene,iSubject] <- names[tmp$Preference[1]]
     
  }
}

row.names(Individual_preferences) <- c('car','meeting','can 0dB SNR','can w/o','traffic')

png('Individual preferences.png',width=1200,height=700)

par(mar=c(4.5, 4, 4 ,5.7))
plot(Individual_preferences,col=c('purple','blue','red','#339900'),ylab = '',xlab = 'Subject',key=list(side=4, cex.axis=1.4), cex.axis=1.5) 
  

dev.off()


```

Now, look at the attributes relative to the preferences: 

```{r}

library('reshape2')
library('dplyr')
library('gridExtra')

#first reshape the shit 
data.raw.reshape <- melt(data.raw,id=c('Subject','Algo','Scene'))
colnames(data.raw.reshape)[4:5] <- c('Attribute','Value')

#data.raw.reshape <- lapply(data.raw.reshape,FUN = as.numeric)

data.raw.PR <- data.raw[data.raw$Preference == '1',] #PR
data.raw.MiE <- data.raw[data.raw$Preference == '2',] #MiE
data.raw.Asym <- data.raw[data.raw$Preference == '3',] #Asym
data.raw.BBF <- data.raw[data.raw$Preference == '4',] #BBF

#aggregate PR
data.raw.PR.reshape <- melt(data.raw.PR,id=c('Subject','Algo','Scene'))
colnames(data.raw.PR.reshape)[4:5] <- c('Attribute','Value')

data.agg.PR <- data.raw.PR.reshape %>% lapply(FUN = as.numeric) %>% aggregate(by=list(data.raw.PR.reshape$Attribute,data.raw.PR.reshape$Algo),
          FUN = 'mean') 

data.agg.PR <- data.agg.PR[data.agg.PR$Attribute != 5,]   #no preference

data.agg.PR$Algo <- as.factor(data.agg.PR$Algo)
data.agg.PR$Attribute <- as.factor(data.agg.PR$Attribute)



#aggregate MiE
data.raw.reshape.MiE <- melt(data.raw.MiE,id=c('Subject','Algo','Scene'))
colnames(data.raw.reshape.MiE)[4:5] <- c('Attribute','Value')

data.agg.MiE <- data.raw.reshape.MiE %>% lapply(FUN = as.numeric) %>% aggregate(by=list(data.raw.reshape.MiE$Attribute,data.raw.reshape.MiE$Algo),
          FUN = 'mean') 

data.agg.MiE <- data.agg.MiE[data.agg.MiE$Attribute != 5,] #no preference

data.agg.MiE$Algo <- as.factor(data.agg.MiE$Algo)
data.agg.MiE$Attribute <- as.factor(data.agg.MiE$Attribute)


#aggregate Asym
data.raw.reshape.Asym <- melt(data.raw.Asym,id=c('Subject','Algo','Scene'))
colnames(data.raw.reshape.Asym)[4:5] <- c('Attribute','Value')

data.agg.Asym <- data.raw.reshape.Asym %>% lapply(FUN = as.numeric) %>% aggregate(by=list(data.raw.reshape.Asym$Attribute,data.raw.reshape.Asym$Algo),
          FUN = 'mean') 

data.agg.Asym <- data.agg.Asym[data.agg.Asym$Attribute != 5,] #no preference

data.agg.Asym$Algo <- as.factor(data.agg.Asym$Algo)
data.agg.Asym$Attribute <- as.factor(data.agg.Asym$Attribute)



#aggregate BBF
data.raw.reshape.BBF <- melt(data.raw.BBF,id=c('Subject','Algo','Scene'))
colnames(data.raw.reshape.BBF)[4:5] <- c('Attribute','Value')

data.agg.BBF <- data.raw.reshape.BBF %>% lapply(FUN = as.numeric) %>% aggregate(by=list(data.raw.reshape.BBF$Attribute,data.raw.reshape.BBF$Algo),
          FUN = 'mean') 

data.agg.BBF <- data.agg.BBF[data.agg.BBF$Attribute != 5,] #no preference

data.agg.BBF$Algo <- as.factor(data.agg.BBF$Algo)
data.agg.BBF$Attribute <- as.factor(data.agg.BBF$Attribute)



#plots
p1 <- data.agg.PR %>%  ggplot(aes(x=Algo, y=Value, fill=Attribute)) +
  geom_bar(stat = 'identity',position = 'dodge',color='black',width = .8) + 
  scale_fill_manual(labels= c('Quality','Effort','Spatialization','Speech'),values=c("purple", "green",'blue','red')) +
  scale_x_discrete(labels = c("2-mic PR", "MiE", "Asym",'BBF')) +
  labs(title = 'Preference: 2-mic PR', x = 'Algo', y = 'Score') +
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        title = element_text(size=19),
        legend.position = c(0.91,0.22)) +
        ylim(c(0,9))
  


p2 <- data.agg.MiE %>%  ggplot(aes(x=Algo, y=Value, fill=Attribute)) +
  geom_bar(stat = 'identity',position = 'dodge',color='black',width = .8) + 
  scale_fill_manual(labels= c('Quality','Effort','Spatialization','Speech'),values=c("purple", "green",'blue','red')) +
  scale_x_discrete(labels = c("2-mic PR", "MiE", "Asym",'BBF')) +
  labs(title = 'Preference: MiE', x = 'Algo', y = 'Score') +
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        title = element_text(size=19),
        legend.position = 'none')+
        ylim(c(0,9))


p3 <- data.agg.Asym %>%  ggplot(aes(x=Algo, y=Value, fill=Attribute))+
  geom_bar(stat = 'identity',position = 'dodge',color='black',width = .8) + 
  scale_fill_manual(labels= c('Quality','Effort','Spatialization','Speech'),values=c("purple", "green",'blue','red')) +
  scale_x_discrete(labels = c("2-mic PR", "MiE", "Asym",'BBF')) +
  labs(title = 'Preference: Asym', x = 'Algo', y = 'Score') +
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        title = element_text(size=19),
        legend.position = 'none') +
        ylim(c(0,9))


p4 <- data.agg.BBF %>%  ggplot(aes(x=Algo, y=Value, fill=Attribute)) +
  geom_bar(stat = 'identity',position = 'dodge',color='black',width = .8) + 
  scale_fill_manual(labels= c('Quality','Effort','Spatialization','Speech'),values=c("purple", "green",'blue','red')) +
  scale_x_discrete(labels = c("2-mic PR", "MiE", "Asym",'BBF')) +
  labs(title = 'Preference: BBF', x = 'Algo', y = 'Score') +
  theme(axis.text=element_text(size=16),
        axis.title=element_text(size=18),
        title = element_text(size=19),
        legend.position = 'none') +
        ylim(c(0,9))


png('Attributes_Preferences.png',width = 1200, height = 800)

grid.arrange(p1,p2,p3,p4,ncol=2,nrow=2)

dev.off()

```

Decision tree: 

```{r}

library('rpart')
library('partykit')





```

